#!/usr/bin/env bash
# Phase 2: Compile.
# Performs the full Maven build (clean package) with the sphinx
# documentation step intact. Validates that every step of the build
# chain succeeds and the four service WARs are produced.
#
# Sphinx is auto-bootstrapped into a Python venv by docs/build_docs.sh
# inside the source tree. python3 must be available on the host PATH.
#
# Network access is required for the initial source clone and for
# Maven dependency resolution; subsequent runs reuse ~/.m2.

set -euo pipefail

readonly TOP="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly SRC_PATH="${TOP}/epicsarchiverap-maven-src"
readonly TARGET_DIR="${SRC_PATH}/target"
readonly MIN_WAR_BYTES=1000000

# shellcheck source=lib/common.bash
source "${TOP}/tests/lib/common.bash"

phase_header "Phase 2: Compile"

# P2.1 Toolchain present.
assert_cmd python3 "python3 available (build_docs.sh venv bootstrap)"
assert_dir "${JAVA_HOME:-/usr/lib/jvm/java-21-openjdk-amd64}" "JAVA_HOME directory"

# P2.2 Source tree: clone via make init when absent, otherwise skip.
if [[ ! -d "${SRC_PATH}" ]]; then
    if run_logged "make init (cloning source)" make -C "${TOP}" init; then
        _record_pass "make init succeeded"
    else
        _record_fail "make init" "see ${LOGFILE}"
    fi
else
    _record_pass "Source tree already present (skipping make init)"
fi
assert_dir "${SRC_PATH}" "source tree at ${SRC_PATH}"
assert_file "${SRC_PATH}/mvnw" "Maven Wrapper present in the source tree"

# P2.3 Full build (sphinx + war + assembly).
if run_logged "make build.mvn (full Maven package, ~1-2 min)" make -C "${TOP}" build.mvn; then
    _record_pass "make build.mvn succeeded"
else
    _record_fail "make build.mvn" "see ${LOGFILE}"
fi

# P2.4 Four service WARs produced and large enough to be plausible.
for service in mgmt engine etl retrieval; do
    war="${TARGET_DIR}/archappl-2025-6-${service}.war"
    assert_file_size_min "${war}" "${MIN_WAR_BYTES}" "${service}.war size"
done

# P2.5 Release assembly tarball produced.
assert_file "${TARGET_DIR}/archappl_2025-6.tar.gz" "release tarball produced"

# P2.6 RELEASE_NOTES generated by the prepare-package phase.
assert_file "${TARGET_DIR}/stage/RELEASE_NOTES" "RELEASE_NOTES staged"

# P2.7 Sphinx HTML output rendered (used by mgmt webapp UI help).
assert_dir "${SRC_PATH}/docs/docs/build" "sphinx docs built"
assert_file "${SRC_PATH}/docs/docs/build/index.html" "sphinx index.html present"

phase_pass "Phase 2: Compile"
