#!/usr/bin/env bash
# Phase 2: Compile.
# Runs the Maven build (clean package, tests skipped) and validates that the
# four service WARs and the release assembly are produced, and that the mgmt
# WAR carries the generated API reference. The test suite runs in the CI at
# https://github.com/jeonghanlee/epicsarchiverap-maven, not here.
#
# Network access is required for the initial source clone and for
# Maven dependency resolution; subsequent runs reuse ~/.m2.

set -euo pipefail

readonly TOP="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly SRC_PATH="${TOP}/epicsarchiverap-maven-src"
readonly TARGET_DIR="${SRC_PATH}/target"
readonly MIN_WAR_BYTES=1000000

# shellcheck source=lib/common.bash
source "${TOP}/tests/lib/common.bash"

phase_header "Phase 2: Compile"

# P2.1 Toolchain present.
assert_dir "${JAVA_HOME:-/usr/lib/jvm/java-21-openjdk-amd64}" "JAVA_HOME directory"

# P2.2 Source tree: clone via make init when absent, otherwise skip.
if [[ ! -d "${SRC_PATH}" ]]; then
    if run_logged "make init (cloning source)" make -C "${TOP}" init; then
        _record_pass "make init succeeded"
    else
        _record_fail "make init" "see ${LOGFILE}"
    fi
else
    _record_pass "Source tree already present (skipping make init)"
fi
assert_dir "${SRC_PATH}" "source tree at ${SRC_PATH}"
assert_file "${SRC_PATH}/mvnw" "Maven Wrapper present in the source tree"

# P2.3 Generate the site overlay through the same configuration target
# used by make build, without provisioning the host storage directories.
if run_logged "make conf.archapplproperties" make -C "${TOP}" conf.archapplproperties; then
    _record_pass "Site configuration generated"
else
    _record_fail "make conf.archapplproperties" "see ${LOGFILE}"
fi

# Full build (war + assembly).
if run_logged "make build.mvn (full Maven package)" make -C "${TOP}" build.mvn; then
    _record_pass "make build.mvn succeeded"
else
    _record_fail "make build.mvn" "see ${LOGFILE}"
fi

# P2.4 A successful clean build produces one WAR per service, with a
# common prefix chosen by the source POM rather than this environment.
shopt -s nullglob
artifact_prefix=""
for service in mgmt engine etl retrieval; do
    wars=("${TARGET_DIR}/"*-"${service}.war")
    assert_eq "${#wars[@]}" "1" "Exactly one ${service}.war"
    war="${wars[0]}"
    assert_file_size_min "${war}" "${MIN_WAR_BYTES}" "${service}.war size"
    prefix="${war%-"${service}".war}"
    if [[ -z "${artifact_prefix}" ]]; then
        artifact_prefix="${prefix}"
    else
        assert_eq "${prefix}" "${artifact_prefix}" "${service}.war shares the build prefix"
    fi
done

# P2.5 The assembly plugin owns the release tarball name.
tarballs=("${TARGET_DIR}/"*.tar.gz)
assert_eq "${#tarballs[@]}" "1" "Exactly one release tarball"
assert_file "${tarballs[0]}" "release tarball produced"

# P2.6 RELEASE_NOTES generated by the prepare-package phase.
assert_file "${TARGET_DIR}/stage/RELEASE_NOTES" "RELEASE_NOTES staged"

# P2.7 The mgmt WAR carries the generated API reference (replaces the retired
# Sphinx docs build): the HTML reference and its machine-readable sibling.
mgmt_wars=("${TARGET_DIR}/"*-mgmt.war)
assert_eq "${#mgmt_wars[@]}" "1" "Exactly one mgmt.war for the API reference check"
api_extract="${TARGET_DIR}/mgmt-api-ref"
rm -rf "${api_extract}"
unzip -q -o "${mgmt_wars[0]}" 'ui/api/*' -d "${api_extract}" || true
assert_file "${api_extract}/ui/api/index.html" "mgmt WAR ui/api/index.html"
assert_file "${api_extract}/ui/api/api.json" "mgmt WAR ui/api/api.json"

phase_pass "Phase 2: Compile"
