#!/usr/bin/env bash
#
#  author  : Jeong Han Lee
#  email   : jeonghan.lee@gmail.com
#  version : 0.0.3


declare -g SC_RPATH;
#declare -g SC_NAME;
declare -g SC_TOP;
declare -g SC_TIME;

SC_RPATH="$(realpath "$0")";
#SC_NAME=${0##*/};
SC_TOP="${SC_RPATH%/*}"
SC_TIME="$(date +%y%m%d%H%M)"


# All runtime values (JAVA_HOME, CATALINA_HOME, CATALINA_OPTS, ARCHAPPL_*,
# EPICS_CA_*) come from archappl.conf, generated by the environment and
# installed next to this script; it is sourced below with set -a.

if [[ ${1:-} != health ]]; then
    set -a
    # shellcheck disable=SC1091,SC1090
    . "${SC_TOP}/archappl.conf"
    set +a

    # Enable core dumps in case the JVM fails
    ulimit -c unlimited
fi

# shutdown_services is not the same as startup_services
# Order is matter. Please don't change their order.
startup_services=("mgmt" "engine" "etl" "retrieval")
shutdown_services=("engine" "retrieval" "etl" "mgmt")

function pushdd { builtin pushd "$@" > /dev/null || exit; }
function popdd  { builtin popd  > /dev/null || exit; }

function get_ip
{
    ip -4 route get 8.8.8.8 | awk \{'print $7'\} | tr -d '\n'
}

# 1 : Archappl installation path : /opt/epicsarchiver
# 2 : Service name : one of mgmt, engine, etl, retrieval
function get_pid
{
    local  archappl_top="$1";shift;
    local  name="$1";shift;
    local  pid;
    pid=$(cat "${archappl_top}/${name}/temp/${name}.pid")
    printf "%12s : pid %6d exists.\n" "${name}" "$pid"
}

# shellcheck disable=SC2120
function startup_archappl
{
    local archappl_top="$1";shift;

    if [ -z "$archappl_top" ]; then
	    archappl_top="${SC_TOP}"
    fi

    # shutdown_services is not the same as startup_services
    # Order is matter
    for service in "${startup_services[@]}"; do
        pushdd "${archappl_top}/${service}"
        rm -rf "temp/${service}.pid"
        bash bin/startup.sh
        popdd
    done
}

# shellcheck disable=SC2120
function shutdown_archappl
{
    local archappl_top="$1";shift;

    if [ -z "$archappl_top" ]; then
	    archappl_top="${SC_TOP}"
    fi

    # shutdown_services is not the same as startup_services
    # Order is matter
    for service in "${shutdown_services[@]}"; do
        pushdd "${archappl_top}/${service}"
        bash bin/shutdown.sh
        rm -rf "temp/${service}.pid"
        popdd
    done  
}

# shellcheck disable=SC2120
function status_archappl
{

    local archappl_top="$1";shift;

    if [ -z "$archappl_top" ]; then
	    archappl_top="${SC_TOP}"
    fi

    local ip_addr="";
    ip_addr=$(get_ip);

    printf ">>> Current Time %s\n" "${SC_TIME}"
    printf ">>> Archiver Appliance Status"
    printf "    http://%s:17665/mgmt/ui/index.html\n" "${HOSTNAME}";
    printf "                        OR\n";
    printf "    http://%s:17665/mgmt/ui/index.html\n" "${ip_addr}";
    printf "                         OR\n";
    printf "    http://%s:17665/mgmt/ui/index.html\n" "localhost";
    
    printf "\n";
    printf ">>> Consult Service Logs \n";
    
    for service in "${startup_services[@]}"; do
        printf "  tail -f %s/%s/logs/archappl_service.log\n" "${archappl_top}" "${service}";
    done  

    printf ">>> Service PIDs \n"
    printf "    All Tomcat processes\n";
    pgrep 'org.apache.catalina.startup.Bootstrap'
    printf "    Archiver Appliance PIDs\n"
    for service in "${startup_services[@]}"; do
        get_pid "${archappl_top}" "${service}";
    done  
    printf "\n";
}


function status_storage
{
    local all=$1; shift;
    printf "\n>>>> Storage Status at %s\n\n" "${SC_TIME}";
    # ARCHAPPL_STORAGE_TOP is defined in archappl.conf
    if [[ $OSTYPE == 'darwin'* ]]; then
        sudo du -c -h -a "${ARCHAPPL_STORAGE_TOP}"
    else
        sudo -E bash -c "du --total --human-readable --time --\"${all}\" \"${ARCHAPPL_STORAGE_TOP}\"";
    fi
    printf "\n";
}

# Read one bounded PID value without deleting the file or signalling its process.
function health_pid {
    local file="$1" value="" fd resolved parent
    # Resolve symlinks before inspecting ancestors: -e alone also fails on EACCES.
    if ! resolved=$(realpath -m -- "$file" 2>/dev/null); then
        printf '%s\n' 'unreadable-pid-path'
        return 2
    fi
    parent="${resolved%/*}"
    while [[ -n $parent ]]; do
        if [[ -d $parent && ! -x $parent ]]; then
            printf '%s\n' 'inaccessible-pid-directory'
            return 2
        fi
        parent="${parent%/*}"
    done
    if [[ ! -e "$file" && ! -L "$file" ]]; then
        printf '%s\n' 'missing-pid-file'
        return 1
    fi
    if [[ ! -f "$file" || ! -r "$file" ]] || ! { exec {fd}< "$file"; } 2>/dev/null; then
        printf '%s\n' 'unreadable-pid-file'
        return 2
    fi
    # Success means a NUL or 64 characters were read; neither is a valid PID file.
    if IFS= read -r -d '' -n 64 value <&"$fd"; then
        exec {fd}<&-
        printf '%s\n' 'invalid-pid-file'
        return 1
    fi
    exec {fd}<&-
    value="${value%$'\n'}"
    value="${value%$'\r'}"
    if [[ ! $value =~ ^[1-9][0-9]{0,9}$ ]]; then
        printf '%s\n' 'invalid-pid-file'
        return 1
    fi
    printf '%s\n' "$value"
}

# Return a live process's start time; inaccessible observations are distinct from absence.
function health_process_start {
    local pid="$1" line=""
    local -a fields=()
    if ! IFS= read -r line 2>/dev/null < "/proc/$pid/stat"; then
        if [[ ! -d /proc/$pid ]]; then
            printf '%s\n' 'missing-process'
            return 1
        fi
        printf '%s\n' 'unreadable-process-state'
        return 2
    fi
    # comm is parenthesized and may contain spaces or closing parentheses.
    read -r -a fields <<< "${line##*) }"
    if [[ ${#fields[@]} -lt 20 || ! ${fields[19]} =~ ^[0-9]+$ ]]; then
        printf '%s\n' 'invalid-process-state'
        return 2
    fi
    case "${fields[0]}" in
        Z|X|x) printf '%s\n' 'dead-process'; return 1 ;;
        R|S|D|T|t|I|P|W|K) ;;
        *) printf '%s\n' 'unknown-process-state'; return 2 ;;
    esac
    printf '%s\n' "${fields[19]}"
}

# Verify executable and complete Tomcat identity arguments between state observations.
function health_process_identity {
    local pid="$1" base="$2" java="$3" home="$4"
    local start finish exe arg value index rc=0 bases=0 homes=0 bootstrap=0
    local -a args=()
    start=$(health_process_start "$pid") || rc=$?
    if (( rc )); then printf '%s\n' "$start"; return "$rc"; fi
    if ! exe=$(readlink -e "/proc/$pid/exe" 2>/dev/null); then
        printf '%s\n' 'unreadable-process-executable'
        return 2
    fi
    if [[ $exe != "$java" ]]; then
        printf '%s\n' 'wrong-java-executable'
        return 1
    fi
    if ! mapfile -d '' -t args 2>/dev/null < "/proc/$pid/cmdline"; then
        printf '%s\n' 'unreadable-process-arguments'
        return 2
    fi
    # Only VM options before the main class establish system properties.
    # Consume option operands so a classpath/module path is never a main class.
    for (( index=1; index<${#args[@]}; index++ )); do
        arg="${args[index]}"
        case "$arg" in
            -cp|-classpath|--class-path|-p|--module-path|--upgrade-module-path|\
            --add-modules|--limit-modules|--add-reads|--add-exports|--add-opens|\
            --patch-module|--enable-native-access|--source)
                index=$((index + 1)) ;;
            -jar|-m|--module|--module=*) break ;;
            -Dcatalina.base=*)
                bases=$((bases + 1))
                value=$(realpath -e -- "${arg#*=}" 2>/dev/null) || value=""
                if [[ $value != "$base" ]]; then
                    printf '%s\n' 'wrong-instance-base'; return 1
                fi ;;
            -Dcatalina.home=*)
                homes=$((homes + 1))
                value=$(realpath -e -- "${arg#*=}" 2>/dev/null) || value=""
                if [[ $value != "$home" ]]; then
                    printf '%s\n' 'wrong-tomcat-home'; return 1
                fi ;;
            -*) ;;
            *)
                if [[ $arg == org.apache.catalina.startup.Bootstrap ]] &&
                    (( index == ${#args[@]} - 2 )) && [[ ${args[index+1]} == start ]]; then
                    bootstrap=1
                fi
                break ;;
        esac
    done
    if (( bases != 1 || homes != 1 || bootstrap != 1 )); then
        printf '%s\n' 'wrong-tomcat-identity'
        return 1
    fi
    finish=$(health_process_start "$pid") || rc=$?
    if (( rc )); then printf '%s\n' "$finish"; return "$rc"; fi
    if [[ $start != "$finish" ]]; then
        printf '%s\n' 'process-changed-during-inspection'
        return 2
    fi
    printf '%s\n' "$start"
}

function health_instance {
    local name="$1" java="$2" home="$3" base file pid again start finish
    local rc=0
    base="${SC_TOP}/${name}"
    file="${base}/temp/${name}.pid"
    if { [[ -d $base && ! -x $base ]] || [[ -d $base/temp && ! -x $base/temp ]]; }; then
        printf '%s pid=- ERROR inaccessible-instance-directory\n' "$name"
        return 2
    fi
    pid=$(health_pid "$file") || rc=$?
    if (( rc )); then
        printf '%s pid=- %s %s\n' "$name" "$([[ $rc == 2 ]] && printf ERROR || printf FAIL)" "$pid"
        return "$rc"
    fi
    base=$(realpath -e -- "$base" 2>/dev/null) || rc=2
    if (( rc == 0 )); then
        start=$(health_process_identity "$pid" "$base" "$java" "$home") || rc=$?
    else
        start='unreadable-instance-path'
    fi
    if (( rc == 0 )); then
        finish=$(health_process_identity "$pid" "$base" "$java" "$home") || rc=$?
        if (( rc )); then
            start="$finish"
        elif [[ $start != "$finish" ]]; then
            start='process-changed-during-inspection'; rc=2
        fi
    fi
    if (( rc == 0 )); then
        again=$(health_pid "$file") || rc=2
        if (( rc )) || [[ $again != "$pid" ]]; then
            start='pid-file-changed-during-inspection'; rc=2
        fi
    fi
    case "$rc" in
        0) printf '%s pid=%s PRESENT verified-process-presence\n' "$name" "$pid" ;;
        1) printf '%s pid=%s FAIL %s\n' "$name" "$pid" "$start" ;;
        *) printf '%s pid=%s ERROR %s\n' "$name" "$pid" "$start" ;;
    esac
    return "$rc"
}

function health_archappl {
    local JAVA_HOME="" CATALINA_HOME="" java="" home="" error="" service rc result=0
    # shellcheck disable=SC1091,SC1090
    if [[ $OSTYPE != linux* ]]; then
        error='linux-process-inspection-required'
    elif [[ ! -f ${SC_TOP}/archappl.conf || ! -r ${SC_TOP}/archappl.conf ]] ||
        ! bash -n "${SC_TOP}/archappl.conf" >/dev/null 2>&1; then
        error='unreadable-or-invalid-configuration'
    elif ! . "${SC_TOP}/archappl.conf" >/dev/null 2>&1; then
        error='configuration-load-failed'
    elif [[ $JAVA_HOME != /* || $CATALINA_HOME != /* ]] ||
        ! java=$(realpath -e -- "${JAVA_HOME}/bin/java" 2>/dev/null) ||
        ! home=$(realpath -e -- "$CATALINA_HOME" 2>/dev/null) || [[ ! -x $java || ! -d $home ]]; then
        error='invalid-runtime-paths'
    fi
    for service in "${startup_services[@]}"; do
        rc=0
        if [[ -n $error ]]; then
            printf '%s pid=- ERROR %s\n' "$service" "$error"
            rc=2
        else
            health_instance "$service" "$java" "$home" || rc=$?
        fi
        if (( rc > result )); then result=$rc; fi
    done
    case "$result" in
        0) printf '%s\n' 'health PRESENT all-four-processes-verified; application-readiness-not-checked' ;;
        1) printf '%s\n' 'health FAIL one-or-more-invalid-instances' ;;
        2) printf '%s\n' 'health ERROR inspection-incomplete' ;;
    esac
    return "$result"
}

# These properties identify a start/stop transition even when ActiveState repeats.
function health_unit_snapshot {
    systemctl show --no-pager --property=LoadState,ActiveState,SubState,Result,MainPID,InvocationID,InactiveExitTimestampMonotonic,InactiveEnterTimestampMonotonic,ActiveEnterTimestampMonotonic,ExecMainStartTimestampMonotonic "$1" 2>/dev/null
}

function health_systemd {
    local unit="$1" self="$2" allowance="$3" before after own key value output="" state="unknown"
    local now started rc=2
    local -A appliance=() monitor=()
    if [[ ! $unit =~ ^[a-zA-Z0-9_.@:-]+\.service$ || ! $self =~ ^[a-zA-Z0-9_.@:-]+\.service$ ||
          ! $allowance =~ ^[0-9]{1,6}$ ]]; then
        printf '%s\n' 'scheduled ERROR invalid-arguments'
        return 2
    fi
    if ! own=$(health_unit_snapshot "$self") || ! before=$(health_unit_snapshot "$unit"); then
        printf '%s\n' 'scheduled ERROR unreadable-unit-state'
        return 2
    fi
    while IFS='=' read -r key value; do
        if [[ $key =~ ^[a-zA-Z]+$ ]]; then monitor[$key]="$value"; fi
    done <<< "$own"
    while IFS='=' read -r key value; do
        if [[ $key =~ ^[a-zA-Z]+$ ]]; then appliance[$key]="$value"; fi
    done <<< "$before"
    now="${monitor[ExecMainStartTimestampMonotonic]:-}"
    if [[ ${monitor[LoadState]:-} != loaded || ${monitor[ActiveState]:-} != activating ||
          ${monitor[MainPID]:-} != "$$" || ! $now =~ ^[1-9][0-9]{0,14}$ ||
          ${appliance[LoadState]:-} != loaded || -z ${appliance[SubState]:-} ||
          -z ${appliance[Result]:-} ]]; then
        printf '%s\n' 'scheduled ERROR invalid-unit-or-invocation-state'
        return 2
    fi
    state="${appliance[ActiveState]:-unknown}"
    case "$state" in
        inactive)
            if [[ ${appliance[Result]:-} == success ]]; then
                output='SKIP appliance-inactive'; rc=3
            else output='FAIL appliance-stop-failed'; rc=1; fi ;;
        deactivating) output='SKIP appliance-stopping'; rc=3 ;;
        failed) output='FAIL appliance-failed'; rc=1 ;;
        active|activating)
            started="${appliance[InactiveExitTimestampMonotonic]:-}"
            if [[ ! $started =~ ^[1-9][0-9]{0,14}$ ]]; then
                output='ERROR invalid-start-timestamp'; rc=2
            elif (( started > now )); then
                output='SKIP appliance-started-during-check'; rc=3
            elif (( now - started < 10#$allowance * 1000000 )); then
                output='SKIP startup-allowance'; rc=3
            elif [[ $state == activating ]]; then
                output='FAIL startup-allowance-exceeded'; rc=1
            else
                rc=0
                output=$(health_archappl) || rc=$?
            fi ;;
        *) output='ERROR unknown-appliance-state'; rc=2 ;;
    esac
    if ! after=$(health_unit_snapshot "$unit"); then
        printf '%s\n' 'scheduled ERROR unreadable-final-unit-state'
        return 2
    fi
    if [[ $before != "$after" ]]; then
        printf '%s\n' 'scheduled SKIP appliance-transition; retry-next-tick'
        return 3
    fi
    printf 'scheduled appliance=%s state=%s\n%s\n' "$unit" "$state" "$output"
    return "$rc"
}

function usage
{
    {
        echo "";
        echo "Usage    : $0  args"
        echo "";
        echo "              possbile args";
        echo "";
        echo "               startup   : startup all services in order";
        echo "               shutdown  : shutdown all services in order ";
        echo "               restartup : shutdown and startup";
        echo "               storage   : show the storage status";
        echo "               status    : show summary for status";      
        echo "               health    : verify all four JVM processes (Linux)";
        echo "               h         : this screen";
        echo "";
        echo " bash $0 startup "
        echo ""
    } 1>&2;
    exit 1;
}



case "$1" in
    health)
        if [[ $# == 1 ]]; then
            health_archappl
        elif [[ $# == 5 && $2 == --systemd ]]; then
            health_systemd "$3" "$4" "$5"
        else
            printf '%s\n' 'health ERROR invalid-arguments'
            exit 2
        fi
        exit $?
        ;;
    startup)
	    startup_archappl
	    ;;
    shutdown)
	    shutdown_archappl
	    ;;
    restart)
	    shutdown_archappl
	    startup_archappl
	    ;;
    status)
	    status_archappl 
	    ;;
    storage)
	    case "$2" in
	        all) status_storage "$2" ;;
	    *)       status_storage      ;;
	    esac
	    ;;
    h);;
    help)
        usage;
        ;;
    *)
	    usage;
    ;;
esac
