
CREATE TABLE IF NOT EXISTS PVTypeInfo ( 
	pvName VARCHAR(255) NOT NULL PRIMARY KEY,
	typeInfoJSON MEDIUMTEXT NOT NULL,
	last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PVAliases ( 
	pvName VARCHAR(255) NOT NULL PRIMARY KEY,
	realName VARCHAR(256) NOT NULL,
	last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ArchivePVRequests ( 
	pvName VARCHAR(255) NOT NULL PRIMARY KEY,
	userParams MEDIUMTEXT NOT NULL,
	last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ExternalDataServers ( 
	serverid VARCHAR(255) NOT NULL PRIMARY KEY,
	serverinfo MEDIUMTEXT NOT NULL,
	last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

